# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4be12c7e033fd31606b152e97c20fd9a8014e064b70984dcaa3c5d62409d4aac66c7536e4621d00afcaac02bda9a5ba2b8cd55b0d11d76da4625b2bd552457b5

test:
  secret_key_base: b5d24b1d3628152fa23ef83a09ffce755faee21095df9a9f80bb3620d2a4b944061c3b053a8ebd01100b591d050b06250815e42f56f48df6898196277bad96d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
